services:
  gateway-service:
    image: gateway-service:latest
    build:
      context: .
      dockerfile: gateway-service/GWSDockerfile
    restart: "no"
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    labels:
      amplicode.image: springboot
  discovery_server:
    image: discovery_server:latest
    build:
      context: .
      dockerfile: discovery_server/Dockerfile
    restart: "no"
    ports:
      - "8761:8761"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    labels:
      amplicode.image: springboot
  log-service:
    image: log-service:latest
    build:
      context: .
      dockerfile: log-service/LogSDockerfile
    restart: "no"
    ports:
      - "8180:8180"
      - "8181:8181"
      - "8182:8182"
    labels:
      amplicode.image: springboot
  user-service:
    image: user-service:latest
    build:
      context: .
      dockerfile: user-service/USDockerfile
    restart: "no"
    ports:
      - "8280:8280"
      - "8281:8281"
      - "8282:8282"
    labels:
      amplicode.image: springboot
  task-service:
    image: task-service:latest
    build:
      context: .
      dockerfile: task-service/TaskSDockerfile
    restart: "no"
    ports:
      - "8380:8380"
      - "8381:8381"
      - "8382:8382"
    labels:
      amplicode.image: springboot